#!/usr/bin/env python3
import subprocess
import re
import sys

print("-> pre-push")

# Auslesen der Commit-Message
par1 = sys.argv[1]
par2 = sys.argv[2]

print(f"Parameter1 : {par1}")
print(f"Parameter2 : {par2}")

# Der Branchname geht über die Comandlne von GeneratorExit
# Mit der Git-Console im Clone Repo kann dies auch ausgeführt werden: git rev-parse --abbrev-ref HEAD
# ---------------------------------------------------------------------------------------------------
current_branch_name = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).strip().decode('utf-8')
print(f"BranchName : {current_branch_name}")

if current_branch_name == 'HEAD':
    sys.exit(0)
if current_branch_name == 'main':
    sys.exit(0)
if current_branch_name == 'develop':
    sys.exit(0)

sys.exit(1)

